"use client";

import { useState } from "react";
import { BookOpenText, ChevronDown, ChevronRight, FolderTree, Layers3, Search } from "lucide-react";
import type { LoreEntry } from "@/lib/lore";
import { wikiCategoryGroups, wikiCategoryInfo } from "@/lib/wiki-categories";

type Navigation = { entries: LoreEntry[]; selectedId: string | null; selectedCategory: string | null; onPortal: () => void; onCategory: (id: string) => void; onArticle: (id: string) => void };

export function WikiTree(props: Navigation) {
  const [search, setSearch] = useState("");
  const [openGroups, setOpenGroups] = useState<string[]>(["people"]);
  const [openCategories, setOpenCategories] = useState<string[]>(["PEOPLE_STUDENTS"]);
  const matches = props.entries.filter((entry) => (entry.title + " " + entry.body).toLocaleLowerCase("fr").includes(search.toLocaleLowerCase("fr")));
  function toggle(items: string[], setItems: (items: string[]) => void, id: string) { setItems(items.includes(id) ? items.filter((item) => item !== id) : [...items, id]); }
  return <aside className="wiki-sidebar wiki-tree"><button type="button" className={!props.selectedId && !props.selectedCategory ? "wiki-tree-home active" : "wiki-tree-home"} onClick={props.onPortal}><BookOpenText size={17} /> Portail SIOVerse <span>{props.entries.length}</span></button><label className="wiki-search"><Search size={16} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Rechercher un article" aria-label="Rechercher un article" /></label>
    {search.trim() ? <nav aria-label="Résultats de recherche" className="wiki-tree-results">{matches.map((entry) => <button type="button" key={entry.id} className={props.selectedId === entry.id ? "active" : ""} onClick={() => props.onArticle(entry.id)}><span>{entry.title}</span><small>{wikiCategoryInfo(entry.category).category.label}</small></button>)}{!matches.length && <p>Aucun article trouvé.</p>}</nav> : <nav aria-label="Arborescence du wiki" className="wiki-tree-branches">{wikiCategoryGroups.map((group) => <div className="wiki-tree-group" key={group.id}><button type="button" className="wiki-tree-group-toggle" aria-expanded={openGroups.includes(group.id)} onClick={() => toggle(openGroups, setOpenGroups, group.id)}>{openGroups.includes(group.id) ? <ChevronDown size={14} /> : <ChevronRight size={14} />} <FolderTree size={15} /> {group.label}</button>{openGroups.includes(group.id) && <div className="wiki-tree-leaves">{group.categories.map((category) => { const items = props.entries.filter((entry) => entry.category === category.id); return <div key={category.id}><button type="button" className={props.selectedCategory === category.id ? "wiki-tree-leaf active" : "wiki-tree-leaf"} onClick={() => { props.onCategory(category.id); if (!openCategories.includes(category.id)) setOpenCategories([...openCategories, category.id]); }}><span>{category.label}</span><small>{items.length}</small></button>{openCategories.includes(category.id) && <div className="wiki-tree-articles">{items.map((entry) => <button type="button" key={entry.id} className={props.selectedId === entry.id ? "active" : ""} onClick={() => props.onArticle(entry.id)}><ChevronRight size={12} /> <span>{entry.title}</span></button>)}{!items.length && <small>Aucun article</small>}</div>}</div>; })}</div>}</div>)}</nav>}
    <div className="wiki-sidebar-note">Explore les branches, puis complète les articles à plusieurs.</div>
  </aside>;
}

export function WikiPortal({ entries, onCategory, onArticle }: { entries: LoreEntry[]; onCategory: (id: string) => void; onArticle: (id: string) => void }) {
  return <div className="wiki-portal"><div className="wiki-portal-hero"><span><Layers3 size={16} /> PORTAIL D’ACCUEIL</span><h2>Bienvenue dans le Wiki <em>SIOVerse</em></h2><p>Le guide vivant de notre classe : portraits, professeurs, lieux, projets et souvenirs. Choisis une branche pour explorer — ou ouvre un article récent.</p><div><strong>{entries.length}</strong> article{entries.length > 1 ? "s" : ""} · <strong>{wikiCategoryGroups.length}</strong> grands domaines</div></div><div className="wiki-portal-title"><FolderTree size={18} /><h3>Explorer l’arborescence</h3></div><div className="wiki-portal-groups">{wikiCategoryGroups.map((group, index) => <section className={"wiki-portal-group wiki-portal-group-" + group.id} key={group.id}><div className="wiki-portal-group-head"><span>0{index + 1}</span><h4>{group.label}</h4></div><p>{group.description}</p><div>{group.categories.map((category) => <button type="button" key={category.id} onClick={() => onCategory(category.id)}><span>{category.label}</span><small>{entries.filter((entry) => entry.category === category.id).length} article{entries.filter((entry) => entry.category === category.id).length > 1 ? "s" : ""}</small><ChevronRight size={15} /></button>)}</div></section>)}</div><div className="wiki-portal-title"><BookOpenText size={18} /><h3>Articles récents</h3></div><div className="wiki-portal-recent">{entries.slice(0, 6).map((entry) => <button type="button" key={entry.id} onClick={() => onArticle(entry.id)}><span>{entry.title}</span><small>{wikiCategoryInfo(entry.category).group.label} / {wikiCategoryInfo(entry.category).category.label}</small><ChevronRight size={17} /></button>)}{!entries.length && <p>Le wiki attend son premier article.</p>}</div><div className="wiki-portal-help"><strong>Comment participer ?</strong><p>Ouvre un article pour améliorer ses sections. Dans le texte, cite un autre article par son titre : un lien apparaît automatiquement. Tu peux aussi écrire <code>[[Nom de l’article]]</code> pour créer un renvoi explicite.</p></div></div>;
}

export function WikiCategoryView({ categoryId, entries, onPortal, onArticle }: { categoryId: string; entries: LoreEntry[]; onPortal: () => void; onArticle: (id: string) => void }) {
  const { group, category } = wikiCategoryInfo(categoryId);
  const items = entries.filter((entry) => entry.category === category.id);
  return <div className="wiki-category-view"><div className="wiki-category-hero"><button type="button" onClick={onPortal}>Portail SIOVerse</button><span> / {group.label} / {category.label}</span><h2>{category.label}</h2><p>{category.description}</p><strong>{items.length} article{items.length > 1 ? "s" : ""}</strong></div><div className="wiki-category-list">{items.map((entry) => <button type="button" key={entry.id} onClick={() => onArticle(entry.id)}><BookOpenText size={20} /><span><strong>{entry.title}</strong><small>{entry.body.replace(/[\n*>\[\]]/g, " ").slice(0, 150)}…</small></span><ChevronRight size={18} /></button>)}{!items.length && <div className="wiki-category-empty"><FolderTree size={30} /><h3>Cette branche est encore vide</h3><p>Tu peux créer un article et le classer ici.</p></div>}</div></div>;
}
